"""``bexa.help()``: an overview of the public API, generated by introspection."""

from __future__ import annotations

import importlib
import inspect

_SECTIONS: list[tuple[str, str]] = [
    ("Open and reduce", "bexa.core.scan"),
    ("Accumulators (bexa.acc)", "bexa.core.reductions"),
    ("Regions of interest", "bexa.core.roi"),
    ("Saving and loading", "bexa.io.cube"),
    ("Format specs", "bexa.io.formats"),
    ("Analysis: preprocessing", "bexa.analysis.preprocess"),
    ("Analysis: rocking curves", "bexa.analysis.rocking"),
    ("Analysis: peaks", "bexa.analysis.peaks"),
    ("Analysis: pump-probe", "bexa.analysis.pump_probe"),
    ("Analysis: registration", "bexa.analysis.registration"),
    ("Analysis: fitting", "bexa.analysis.fitting"),
    ("Analysis: segmentation", "bexa.analysis.segmentation"),
    ("Analysis: fields", "bexa.analysis.fields"),
    ("Geometry", "bexa.geometry.transforms"),
    ("Crystal", "bexa.crystal.lattice"),
    ("Diffractometer", "bexa.crystal.diffractometer"),
    ("Optics", "bexa.optics.conversions"),
    ("Plots: images", "bexa.viz.images"),
    ("Plots: curves", "bexa.viz.curves"),
    ("Plots: maps", "bexa.viz.maps"),
    ("Plots: volumes", "bexa.viz.volume"),
    ("Plots: interactive", "bexa.viz.interactive"),
    ("Animation", "bexa.viz.animation"),
    ("Pipelines", "bexa.pipelines"),
]


def _first_line(obj: object) -> str:
    doc = inspect.getdoc(obj) or ""
    return doc.splitlines()[0] if doc else ""


def help(section: str | None = None, verbose: bool = False) -> str:  # noqa: A001
    """Return (and print) a compact listing of the public API.

    Parameters
    ----------
    section
        Only show sections whose title contains this text (case-insensitive).
    verbose
        Include private names.
    """
    lines: list[str] = []
    for title, module_name in _SECTIONS:
        if section and section.lower() not in title.lower():
            continue
        try:
            module = importlib.import_module(module_name)
        except Exception as exc:  # optional dependency missing, module not built yet
            lines.append(f"{title}  ({module_name}: unavailable, {exc})")
            continue
        lines.append(f"{title}  ({module_name})")
        public = getattr(module, "__all__", None) or [
            n for n in dir(module) if verbose or not n.startswith("_")
        ]
        for name in public:
            obj = getattr(module, name, None)
            if obj is None or inspect.ismodule(obj):
                continue
            if not (inspect.isfunction(obj) or inspect.isclass(obj)):
                continue
            if getattr(obj, "__module__", module_name) != module_name and not verbose:
                continue
            try:
                sig = str(inspect.signature(obj))
            except (TypeError, ValueError):
                sig = "(...)"
            if len(sig) > 60:
                sig = sig[:57] + "..."
            lines.append(f"    {name}{sig}")
            summary = _first_line(obj)
            if summary:
                lines.append(f"        {summary}")
        lines.append("")
    text = "\n".join(lines)
    print(text)
    return text
